### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by capfei** [ERijck/FuzzyTM#3]
For https://pypi.org/project/FuzzyTM/2.0.5/, the setup.py states GPL 3.0 but the included LICENSE file is GPL 2.0. Is the license GPL 2.0 or GPL 3.0?

**Comment by ERijck** [comment]
Hi Capfei, sorry for my late reply. It seems that you solved the issue. Thanks!

**Comment by capfei** [comment]
@ERijck Sorry for my late response. I would love your definitive answer!
