### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by Yanall-Boutros** [ERijck/FuzzyTM#4]
I just installed FuzzyTM by first:
`pip3 install FuzzyTM`

Then, in an interpreted environment

`>>> import FuzzyTM`

`ModuleNotFoundError: No module named 'gensim'`

Trying `pip3 install gensim` and running again,

`>>>import FuzzyTM`
`    from gensim._matutils import logsumexp, mean_absolute_difference, dirichlet_expectation
  File "gensim/_matutils.pyx", line 1, in init gensim._matutils
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
`

**Comment by ERijck** [comment]
Hi Yanall-Boutros, 

This seems to be an issue with versions. Can you tell me which gensim version and which FuzzyTM version you have installed? 
You can do this by running `pip list `.

**Comment by Yanall-Boutros** [comment]
`pip list | grep gensim`

Outputs version 4.2.0

Thanks for getting back to me, I'll make a docker container for this after I get it working
